# Generated by Django 3.0.7 on 2020-06-25 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone_celular', models.CharField(default='', max_length=255, null=True)),
                ('telefone_fixo', models.CharField(default='', max_length=255, null=True)),
                ('cpf', models.CharField(default='', max_length=255, null=True)),
                ('rg', models.CharField(default='', max_length=255, null=True)),
                ('email', models.CharField(default='', max_length=255, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbUsuario',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Usuario')),
            ],
            options={
                'db_table': 'tbAdministrador',
            },
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Usuario')),
                ('crp', models.CharField(max_length=50)),
                ('perfil', models.TextField(default='')),
                ('verificado', models.BooleanField(default=False)),
                ('foto', models.ImageField(default='imagens/None/no-img.jpg', upload_to='imagens/')),
            ],
            options={
                'db_table': 'tbColaborador',
            },
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Usuario')),
                ('data_nascimento', models.DateField(null=True)),
                ('orientacao_sexual', models.CharField(choices=[('HOMO', 'Homossexual'), ('INDEFINIDO', 'Prefiro não informar'), ('HETERO', 'Heterossexual'), ('BI', 'Bissexual')], max_length=10, null=True)),
            ],
            options={
                'db_table': 'tbPaciente',
            },
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[(3, 'Terça-Feira'), (4, 'Quarta-Feira'), (2, 'Segunda-Feira'), (1, 'Domingo'), (6, 'Sexta-Feira'), (7, 'Sábado'), (5, 'Quinta-Feira')], max_length=1)),
                ('hora', models.CharField(max_length=5)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='horarios', to='core.Colaborador')),
            ],
            options={
                'db_table': 'tbHorario',
            },
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=255)),
                ('descricao', models.CharField(default='', max_length=255, null=True)),
                ('colaboradores', models.ManyToManyField(to='core.Colaborador')),
            ],
            options={
                'db_table': 'tbEspecialidade',
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('ANALISE', 'Em Análise'), ('REALIZADO', 'Realizado'), ('ACEITO', 'Aceito'), ('CANCELADO', 'Cancelado')], max_length=50)),
                ('motivo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('PLANTAO', 'Plantão'), ('PSICOTERAPIA', 'Psicoterapia')], max_length=50)),
                ('colaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agendamentos', to='core.Colaborador')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agendamentos', to='core.Paciente')),
            ],
            options={
                'db_table': 'tbAgendamento',
            },
        ),
    ]
